AWSTemplateFormatVersion: 2010-09-09
Description: Example of Password Generator

Parameters:
  SQLRequestLambdaName:
    Description: SQL Request Lambda name
    Type: String
  VPCId:
    Description: VPC of you database
    Type: AWS::EC2::VPC::Id
  Bucket:
    Description: Bucket for the SQL file is stored
    Type: String
  Key:
    Description: Key in Bucket for the SQL file is stored
    Type: String

Resources:

  DatabaseSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Limits security group egress traffic
      VpcId: !Ref VPCId
      SecurityGroupIngress:
        - CidrIp: 0.0.0.0/0
          FromPort: 3306
          ToPort: 3306
          IpProtocol: TCP

  Database:
    Type: AWS::RDS::DBInstance
    Version: '1.0'
    Properties:
      AllocatedStorage: 5
      DBInstanceClass: db.t2.micro
      Engine: mysql
      EngineVersion: 5.6.22
      DBName: mydb
      MasterUsername: myuser
      MasterUserPassword: mypassword
      StorageType: standard
      VPCSecurityGroups:
        - !Ref DatabaseSecurityGroup

  DatabaseSchema:
    Type: Custom::SQLRequest
    Version: '1.0'
    Properties:
      ServiceToken: !Join [':', ['arn:aws:lambda', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'function', !Ref SQLRequestLambdaName ]]
      Host: !GetAtt Database.Endpoint.Address
      Port: !GetAtt Database.Endpoint.Port
      User: myuser
      Password: mypassword
      Database: mydb
      Engine: mysql
      Request:
        Bucket: !Ref Bucket
        Key: !Ref Key

  DatabaseInsert:
    Type: Custom::SQLRequest
    Version: '1.0'
    DependsOn: DatabaseSchema
    Properties:
      ServiceToken: !Join [':', ['arn:aws:lambda', !Ref 'AWS::Region', !Ref 'AWS::AccountId', 'function', !Ref SQLRequestLambdaName ]]
      Host: !GetAtt Database.Endpoint.Address
      Port: !GetAtt Database.Endpoint.Port
      User: myuser
      Password: mypassword
      Database: mydb
      Engine: mysql
      Request:
        Code: |
          INSERT INTO users (firstname, lastname) VALUES ('John', 'Doe');
          INSERT INTO users (firstname, lastname) VALUES ('Sam', 'Hunter');
